#!/usr/bin/env bash

LOGFILE=$(mktemp /tmp/clang-stderr.XXXXXX)

echo "$@" > "$LOGFILE"
clang "$@" 2> >(tee -a "$LOGFILE" >&2)
EXITCODE=$?

if [ $EXITCODE -eq 0 ]; then
    rm "$LOGFILE"
else
    echo "Clang exited with code $EXITCODE. See $LOGFILE for details." >&2
fi

exit $EXITCODE
