# SPDX-License-Identifier: GPL-2.0
ifdef CONFIG_DEPSAN
depsan-cflags := -fsanitize=lkmm-dep-checker -fsanitize-lkmm-dep-checker-outdir=${LKMM_OUTDIR} -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-memmove -D__DISABLE_EXPORTS -ftrivial-auto-var-init="zero" -ftime-report

export CFLAGS_DEPSAN := $(depsan-cflags)
endif # CONFIG_DEPSAN
